- id: doc-builder-style
  name: Check style with doc-builder
  description: Style docstrings in Python files and code examples in mdx files.
  entry: doc-builder style
  language: python
  types_or: [python, mdx]
