name: Delete Doc Comment Trigger

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: string

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        shell: bash
        run: |
          mkdir build_dir

      - name: Save pr_number
        run: echo ${{ inputs.pr_number }} > ./build_dir/pr_number

      - uses: actions/upload-artifact@v3
        with:
          name: doc-delete-artifact
          path: build_dir/