name: Delete old PRs docs
on:
  workflow_dispatch:
  schedule:
    - cron: "11 11 * * *"

defaults:
  run:
    working-directory: scripts

jobs:
  delete_old_prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d  # v1.5.2
        with:
          deno-version: v1.x
      - name: Install hf CLI
        run: pip install -U huggingface_hub
      - run: deno run --allow-env --allow-net --allow-run --allow-read ./delete-old-prs.ts
        env:
          HF_ACCESS_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
