name: SvelteKit Lint
on:
  pull_request:
    paths:
      - "kit/**"
      - ".github/workflows/lint-svelte-kit.yml"
  push:
    branches:
      - main

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: kit/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: kit

      - name: Checking lint/format errors
        run: npm run lint
        working-directory: kit

      - name: Checking type errors
        run: npm run check
        working-directory: kit