name: Populate Search Engine

on:
  schedule:
    - cron: "5 7 * * *" # every day at 07:05
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  process-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Set timeout to 6 hours
    steps:
      - name: Checkout doc-builder
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install doc-builder
        run: uv sync --extra dev

      - name: Populate search engine from HF doc-build dataset
        env:
          HF_IE_URL: ${{ secrets.HF_IE_URL }}
          HF_IE_TOKEN: ${{ secrets.HF_IE_TOKEN }}
          MEILISEARCH_KEY: ${{ secrets.MEILISEARCH_KEY }}
          MEILISEARCH_URL: ${{ secrets.MEILISEARCH_URL }}
          HF_TOKEN: ${{ secrets.HF_EMBED_DATASETS_TOKEN }}
        run: uv run doc-builder populate-search-engine --incremental
